matrix:
  IMAGE:
    - jessie
    - wheezy

build:
  image: armhfbuild/docker:1.9.1-dind
  privileged: true
  commands:
    - docker daemon &
    - apk add --update bash debootstrap make
    - make $$IMAGE.tar

publish:
  jessie:
    image: armhfplugins/drone-docker
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/debian
    tag:
      - "8.3"
      - "8"
      - jessie
      - latest
    build_args:
      - IMAGE_TAR=$$IMAGE.tar
    when:
      matrix:
        IMAGE: jessie

  wheezy:
    image: armhfplugins/drone-docker
    username: $$DOCKER_USER
    email: $$DOCKER_EMAIL
    password: $$DOCKER_PASSWORD
    repo: armhfbuild/debian
    tag:
      - "7.9"
      - "7"
      - wheezy
    build_args:
      - IMAGE_TAR=$$IMAGE.tar
    when:
      matrix:
        IMAGE: wheezy

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK_URL
    channel: armhf
